[package]
name = "features-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
default = ["optional_feature", "with_f1"]
optional_feature = []
with_f1 = []
without_f1 = []
